:white_check_mark: Polyfill onlyMethods since PHUnit 8.3
```
Error: Call to undefined method PHPUnit\Framework\MockObject\MockBuilder::setMethods()
```